project_name: snippy
version: 2
before:
  hooks:
    - go mod tidy
    - pnpm install
    - pnpm codegen
builds:
  - env: [CGO_ENABLED=1]
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
checksum:
  name_template: "checksums.txt"
dockers:
  - goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"

    dockerfile: release.Dockerfile
    image_templates:
      - ghcr.io/alindesign/snippy:{{ .Tag }}-amd64
      - ghcr.io/alindesign/snippy:latest-amd64
  - goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

    dockerfile: release.Dockerfile
    image_templates:
      - ghcr.io/alindesign/snippy:{{ .Tag }}-arm64
      - ghcr.io/alindesign/snippy:latest-arm64
docker_manifests:
  - name_template: ghcr.io/alindesign/snippy:{{ .Tag }}
    image_templates:
      - ghcr.io/alindesign/snippy:{{ .Tag }}-amd64
      - ghcr.io/alindesign/snippy:{{ .Tag }}-arm64
  - name_template: ghcr.io/alindesign/snippy:latest
    image_templates:
      - ghcr.io/alindesign/snippy:latest-amd64
      - ghcr.io/alindesign/snippy:latest-arm64
